# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 173fefa61053e6d2e90ae677c69b25d086506d75f397ee9a061b22ca48fe7a8b677b40baf0d831fa57585091280a8b67b8216e193af5a7d33a60118d4842d3de

test:
  secret_key_base: 46b2eea996cfcb84a244ef5f3091185339e93143b8534d4bcb8f3c6deb9006f9f8d077d30787bbc7a300dd6bcbfc7d4ef41a7cdfb4bad4997b680f4a6a3b6401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
